Repository awesome-foss/awesome-sysadmin, pull requests merged in 2022-10, with the labels that each got.

#402 update pull request template with new guidelines
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: reviewers wanted, curation

#403 add aptly to Packaging
  README.md
Labels: reviewers wanted, addition

#413 update atom editor
  README.md
Labels: curation

#412 remove rdp wrap as it is dead
  README.md
Labels: curation

#410 Update limetext link
  README.md
Labels: curation

#397 Add Nomad to Cloud Orchestration list
  README.md
Labels: reviewers wanted, addition
