Repository awesome-foss/awesome-sysadmin, pull requests merged in 2023-04, with the labels that each got.

#467 Log management: cleanup, formatting, remove unmaintained and non-Free software
  README.md
Labels: curation

#470 databases: add external link to awesome-selfhosted/Database Management
  README.md
Labels: curation

#468 log management: add rsyslog
  README.md
Labels: reviewers wanted, addition

#471 Cleanup/improve Web section, remove Cherokee and uWSGI
  README.md
Labels: curation

#476 Fix: Changed Traefik language (C -> Go)
  README.md
Labels: curation

#472 Automation section: add source code link, license, and language/platform tag
  README.md
Labels: reviewers wanted, curation

#477 Update README.md
  README.md
Labels: curation

#474 Cleanup/update DNS sections
  README.md
Labels: curation
