Repository awesome-foss/awesome-sysadmin, pull requests merged in 2023-11, with the labels that each got.

#515 Added HestiaCP to Server Control Panel
  README.md
Labels: addition

#539 Remove VestaCP (unmaintained since 2022)
  README.md
Labels: curation

#510 Add openITCOCKPIT to Monitoring section
  README.md
Labels: addition

#542 tools: move all CI workflows and automation to separate repository
  .github/workflows/ci.yml
  .gitignore
  .hecat/awesome-lint.yml
  .hecat/import.yml
  .hecat/url-check.yml
  Makefile
  markdown/footer.md
  markdown/header.md
Labels: tools

#544 remove GolangCI (the project is archived)
  README.md
Labels: curation

#545 remove CapsuleCD (the project is archived)
  README.md
Labels: curation
