Repository awesome-foss/awesome-sysadmin, pull requests merged in 2023-09, with the labels that each got.

#521 Add Source Code & Licenses to almost all Software
  README.md
Labels: enhancement

#523 Add missing section descriptions
  .hecat/awesome-lint.yml
  Makefile
  README.md
Labels: curation, fix, enhancement

#526 Fix most syntax errors
  README.md
Labels: fix

#527 Remove Cabot (unmaintained)
  README.md
Labels: curation

#528 move remaining Cloud Computing items to Deployment Automation
  README.md
Labels: fix

#513 Add glances to monitoring
  README.md
Labels: addition

#529 Update Links to GitLab CI
  README.md
Labels: curation, fix

#531 Remove Atomia DNS website
  README.md
Labels: fix

#533 Exclude openvpn from url check
  .hecat/url-check.yml
Labels: fix

#530 Fix Ceph URL
  README.md
Labels: fix

#536 Remove leading slash from openvpn url check
  .hecat/url-check.yml
Labels: fix

#535 Add Environment Modules to Build and software organization tools
  README.md
Labels: reviewers wanted, addition

#537 Update README to fix Bolt link
  README.md
Labels: fix
