Repository awesome-foss/awesome-sysadmin, pull requests merged in 2023-07, with the labels that each got.

#507 Service Discovery/Software Containers: add source code links, licenses, language/platform tags, remove dead projects
  README.md
Labels: curation

#508 Rename Remote Management section to Remote Desktop Clients
  README.md
Labels: curation, fix

#498 Add authentik to SSO
  README.md
Labels: reviewers wanted, addition

#511 external links: websites: standardize formatting/shorten description
  README.md
Labels: enhancement

#501 Added kroki.io to diagramming chapter
  README.md
Labels: reviewers wanted, addition

#514 Fix demo link for "dashdot" in Monitoring software
  README.md
Labels: fix

#512 add links to CNCF landscape, various cleanup tasks
  README.md
Labels: curation, enhancement
