Repository awesome-foss/awesome-sysadmin, pull requests merged in 2023-03, with the labels that each got.

#459 pull request template: additional questions to help evaluate actual awesomeness of projects
  .github/PULL_REQUEST_TEMPLATE.md
Labels: reviewers wanted, curation, discussion

#421 Add podman
  README.md
Labels: addition

#357 PiVPN Added
  README.md
Labels: addition

#422 Add systemd nspawn
  README.md
Labels: addition

#452 Add Status to Monitoring software
  README.md
Labels: reviewers wanted, addition

#453 Add Authelia to Identity Management - Single Sign-On (SSO)
  README.md
Labels: addition

#457 Add 'dar' to 'Backups'
  README.md
Labels: addition

#393 Add Dockovpn to VPN list
  README.md
Labels: reviewers wanted, addition

#462 replace travis CI with github actions (check syntax, check links)
  .github/workflows/ci.yml
  .hecat/awesome-lint.yml
  .hecat/import.yml
  .hecat/url-check.yml
  .travis.yml
  Makefile
Labels: curation

#438 add lldap to ldap
  README.md
Labels: addition

#463 LDAP: add source code links, licenses, languages, update URLs and descriptions
  README.md
Labels: curation

#464 project maintenance has resumed, consider contributing to pinned issues
  README.md
Labels: curation
