Repository awesome-foss/awesome-sysadmin, pull requests merged in 2023-06, with the labels that each got.

#495 Fix PR Template repo link leading to itself
  .github/PULL_REQUEST_TEMPLATE.md
Labels: fix

#489 Add JuiceFS to Distributed Filesystems
  README.md
Labels: reviewers wanted, addition

#490 Metrics & Metric Collection: cleanup, formatting, remove dead links, add licenses/languages
  README.md
Labels: curation

#499 Distributed filesystems: add source code links, licenses, languages/platforms, remove unmaintained projects
  README.md
Labels: curation

#494 Add Proxmox Backup Server to Backups
  README.md
Labels: addition

#493 Add pfSense CE to Router
  README.md
Labels: reviewers wanted, addition

#491 Add ruptime to Monitoring
  README.md
Labels: addition

#481 Cleanup, formatting, add source code URLs, licenses, languages
  README.md
Labels: curation

#502 Cleanup, formatting, add licenses/source code links/languages, remove unmaintained projects
  README.md
Labels: curation, fix

#503 DNS: group Control Panels and Domain Management subsections, cleanup
  README.md
Labels: curation

#504 move nsupdate.info/SPF Toolbox from awesome-selfhosted/DNS to DNS - Control Panels & Domain Management
  README.md
Labels: curation

#505 Remove Pi-Hole (moved to awesome-selfhosted/DNS)
  README.md
Labels: curation
