Repository awesome-foss/awesome-sysadmin, pull requests merged in 2024-08, with the labels that each got.

#588 Fix URL for Firezone
  README.md
Labels: fix

#589 move Web Servers section to awesome-selfhosted
  README.md
Labels: enhancement

#557 Add Gluetun to VPN
  README.md
Labels: reviewers wanted, addition
