Repository awesome-foss/awesome-sysadmin, pull requests merged in 2024-05, with the labels that each got.

#570 add PaaS section, move items from awesome-selfhosted
  README.md
Labels: enhancement

#571 remove rabbitmq and kafka
  README.md
Labels: duplicate, curation

#540 Add Wazuh to monitoring section (No other relavant section for SIEMs)
  README.md
Labels: addition

#573 Remove Vlad the Deployer (unmaintained since 2020)
  README.md
Labels: curation

#574 remove Mina (unmaintained since Oct 2023)
  README.md
Labels: curation

#575 remove DrawThe.Net (unmaintained since 2017)
  README.md
Labels: curation

#576 remove perf-tools (unmaintained since 2020)
  README.md
Labels: curation

#577 remove Hiawatha (unmaintained since Oct 2023)
  README.md
Labels: curation

#578 remove Tinc (unmaintained since 2021)
  README.md
Labels: curation

#579 remove IndieAuth (unmaintained since 2021)
  README.md
Labels: curation
